-- Step 1: Create table
CREATE TABLE IF NOT EXISTS guests (
  id         VARCHAR(36)  PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255),
  type       VARCHAR(10)  DEFAULT 'regular',
  code       VARCHAR(7)   UNIQUE,
  arrived    BOOLEAN      DEFAULT false,
  arrived_at TIMESTAMP    DEFAULT NULL
);

-- Step 2: If table already exists without code column, add it
ALTER TABLE guests ADD COLUMN IF NOT EXISTS code VARCHAR(7) UNIQUE;

-- Step 3: Insert all guests with their codes
INSERT INTO guests (id, name, type, code) VALUES
('g-116', 'James Bajee', 'vip', 'TALZUCI'),
('g-001', 'Fuad Abdi', 'vip', 'EKKBC1S'),
('g-002', 'Dr. Johnson Mwangi', 'vip', 'KZOTKIC'),
('g-003', 'Mrs. Florence Kinuthia', 'vip', 'XKYGQWF'),
('g-004', 'Daniel Mwangi Kinuthia', 'vip', 'MNJBUQJ'),
('g-005', 'Ruth Mwouria', 'vip', 'NZ6V6B1'),
('g-006', 'Shadrack Njoroge', 'vip', '8JMHOA0'),
('g-007', 'Cornelius Nyangres', 'vip', 'BL6HTBO'),
('g-008', 'Redempter Mwongeli', 'vip', 'BNI5IKT'),
('g-009', 'Suzan Nyatega', 'vip', 'PMVZLYG'),
('g-010', 'Catherine Wambui', 'vip', 'CF8WKKJ'),
('g-011', 'Pamela Keen', 'vip', 'CDREJGO'),
('g-012', 'Dharmesh Savla', 'vip', 'JQ7KZIF'),
('g-013', 'Mr. Samuel Irungu', 'vip', '7O3GTIB'),
('g-014', 'Dr. Destaings Nyongesa', 'vip', 'MNOTTDX'),
('g-015', 'Charles Lenjo Mwazighe', 'vip', 'XAKXDUH'),
('g-016', 'Steve Waudo', 'vip', 'XSCB5BT'),
('g-017', 'Grace Major', 'vip', 'HFBSHAF'),
('g-018', 'George Adalla', 'vip', 'GEWEOKT'),
('g-019', 'Jocelyn Omusembe', 'vip', 'UDAZ8JK'),
('g-020', 'Maurice Nandwa', 'regular', 'SYX4MBZ'),
('g-021', 'PEL Catherine Salt Div', 'regular', '8T38QGI'),
('g-022', 'Doreen Daria Marube', 'regular', 'MET1GBS'),
('g-023', 'Wangu Mathu', 'regular', 'RGBUIIG'),
('g-024', 'William Mathu', 'regular', 'TNRMNHU'),
('g-025', 'Claudius Chepkemoi', 'regular', 'HKD0GGN'),
('g-026', 'Shafana Kanani', 'regular', 'INOQUIP'),
('g-027', 'Rizwan Kanani', 'regular', 'B99GQPI'),
('g-028', 'Hellen Nyokabi', 'regular', 'NZL9LO0'),
('g-029', 'S Mboyano', 'regular', '0BXRMYK'),
('g-030', 'Peace Wambua', 'regular', 'LMFO4VR'),
('g-031', 'Dorothy Wambua', 'regular', 'Q1BLSWZ'),
('g-032', 'Daniel Wambua', 'regular', 'NI5GFFA'),
('g-033', 'Susan Gitau', 'regular', 'KMNCPPV'),
('g-034', 'Jareth Kinyanjui', 'regular', '0KS2GCS'),
('g-035', 'Onesmus Kevin', 'regular', 'VK4IJDW'),
('g-036', 'Martin Mogusu', 'regular', 'LUWKGKW'),
('g-037', 'Rachael Mogusu', 'regular', 'KF24VFB'),
('g-038', 'Ashina Wanga', 'regular', 'U9SHZ2S'),
('g-039', 'Osborne Wanyoike', 'regular', 'UAC8NRY'),
('g-040', 'Anastasia Kibutu', 'regular', '2IZTFJP'),
('g-041', 'Angela Mueni Munyasya', 'regular', 'OXYAHPS'),
('g-042', 'Annette Khasandi Wanyoike', 'regular', 'HSWBXMG'),
('g-043', 'Melanie Maina', 'regular', 'XUDYKI2'),
('g-044', 'Zuri Hedaya Monari', 'regular', 'VERWDM6'),
('g-045', 'Albert Kioko', 'regular', 'UQNCCHC'),
('g-046', 'Brian Kintei', 'regular', 'KRG4MBK'),
('g-047', 'Jean Munga', 'regular', 'LD5JPO9'),
('g-048', 'Anita Mutula', 'regular', 'VZHDS2P'),
('g-049', 'Brenda Nzula Mutua', 'regular', 'P2HNW8V'),
('g-050', 'Christine Katunge Kitale', 'regular', 'QQXVSWW'),
('g-051', 'Ann Mumbua', 'regular', 'UCFUGLP'),
('g-052', 'Peter Mogere', 'regular', 'FBMXCD9'),
('g-053', 'Njeri Wanjau', 'regular', 'T4GBRG0'),
('g-054', 'Jane Mukabi', 'regular', '1AMLSWY'),
('g-055', 'Ava Njeri Goro', 'regular', 'N3AFP6E'),
('g-056', 'Florence Mwithaga Minua', 'regular', 'UHBIBNH'),
('g-057', 'Margaret Njeri Maina', 'regular', 'LNUQOII'),
('g-058', 'Margaret Wagio Minua', 'regular', '9O3YZLF'),
('g-059', 'Ruth Wanjiru Minua', 'regular', '4B1PZ0Z'),
('g-060', 'Rose Wanjiru Kanyugi', 'regular', 'EO0DHKP'),
('g-061', 'Assumpta Ndunge', 'regular', '4U9GSOO'),
('g-062', 'Mr. Musika Raymond', 'regular', '4FY787Q'),
('g-063', 'Jane Waithira', 'regular', 'LWLATGY'),
('g-064', 'Rosemary Muringi', 'regular', 'QH3ZP2W'),
('g-065', 'Ronny Gichuki', 'regular', 'TDAB8YN'),
('g-066', 'Esther Wangombe', 'regular', 'ZGZMQPO'),
('g-067', 'Wanjohi Wangombe', 'regular', 'WF8XGYR'),
('g-068', 'Leonard Lihanda', 'regular', 'TCOBJ3L'),
('g-069', 'John Keverenge', 'regular', 'QHXNGFK'),
('g-070', 'Shadrack Mugazia', 'regular', 'ZTBMPCY'),
('g-071', 'Abdullahi Bashir', 'regular', 'O8W4QCX'),
('g-072', 'Jason Tevin', 'regular', 'REH0WYH'),
('g-073', 'Angela Ariko', 'regular', 'RP5FI9W'),
('g-074', 'Nyanchama Ogoti', 'regular', 'QWLDIAC'),
('g-075', 'Schola Wangeci', 'regular', 'OMFL2V9'),
('g-076', 'Sarah Kaminchia', 'regular', 'T9RHVKP'),
('g-077', 'Rose Ayuma', 'regular', 'O61GK4H'),
('g-078', 'Monica Achieng Omondi', 'regular', 'I6XWO6P'),
('g-079', 'Edith Onyango', 'regular', 'O6DHDWN'),
('g-080', 'David Musyoki', 'regular', 'QSRZHUK'),
('g-081', 'Kenneth Gatheca', 'regular', 'KMTI3RR'),
('g-082', 'Lillian Oluoch', 'regular', 'LP6XX9Z'),
('g-083', 'Merina Adhiaya', 'regular', 'ILAMCAC'),
('g-084', 'Selina Lwaki', 'regular', 'WOXSOEV'),
('g-085', 'Mr. George Wadegu', 'regular', 'SMC4GD7'),
('g-086', 'Andrew Wambua', 'regular', '6SLM1ZM'),
('g-087', 'Charles N Mwania', 'regular', '3C7S7CF'),
('g-088', 'Shalney Sirintai', 'regular', '0TAYFOW'),
('g-089', 'Sylvia Mantaine Kamoye', 'regular', 'MBSXNLX'),
('g-090', 'Estther Kithuku', 'regular', 'R5JTCEP'),
('g-091', 'Dr. Daniel Muindi', 'regular', 'BBKEQEZ'),
('g-092', 'Mrs. Winnie Muindi', 'regular', 'KVCUOYH'),
('g-093', 'Prof. Kyallo Wamitila', 'regular', '5K1LUXA'),
('g-094', 'Dr. Florence Muthiani', 'regular', 'EBPOX6G'),
('g-095', 'Victoria Mutile Kithuku', 'regular', '7MVSEES'),
('g-096', 'John Kibet', 'regular', '5TB3FOC'),
('g-097', 'Steve Tele', 'regular', 'N691KR8'),
('g-098', 'Audrey Achieng', 'regular', 'QNRCLWY'),
('g-099', 'Kenneth Kiura Njora', 'regular', 'DQW9OPJ'),
('g-100', 'Christine Katunge Kitale (2)', 'regular', 'OGAS21R'),
('g-101', 'Grace Kiyuka', 'regular', 'S5XZOFN'),
('g-102', 'Caroline Mutuota', 'regular', 'ODLAV7P'),
('g-103', 'Clinton', 'regular', 'R7IK3JQ'),
('g-104', 'Rosemary Baraza', 'regular', '65OF69K'),
('g-105', 'Alice Wahome', 'regular', '2SZRTNP'),
('g-106', 'Levis Njiru', 'regular', 'EWXA2G1'),
('g-107', 'Rosie Mueni', 'regular', 'L9QM7KF'),
('g-108', 'Divinah Moragwa', 'regular', 'MBMSKTL'),
('g-109', 'Edwin Binale', 'regular', 'HHUVRXB'),
('g-110', 'Cindy Mutuota', 'regular', 'REMZNNZ'),
('g-111', 'Rosebella Onyango', 'regular', 'T5LMMEN'),
('g-112', 'Caroline Kangogo', 'regular', 'VJTPRCT'),
('g-113', 'Veronica Maina', 'regular', 'ITN03HW'),
('g-114', 'Moses Nderitu', 'regular', 'L7B9RNE'),
('g-115', 'Nicole Muthoni', 'regular', 'ZUJBCP4')
ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code;
